### ISSUE TITLE
Question about training backbone

### ISSUE THREAD

**Issue by WindFall-wyx** [allenhaozhu/EASE#1]
Hello, although your work is based on extracted features and providing download link, I'm still interested in how you train the backbone. Could you tell me the detailed training methods or the github project you referred to? Thank you.

**Comment by allenhaozhu** [comment]
Sorry to reply you so late. Usually we prefer to use the S2M2 ([Manifold Mixup for Few-shot Learning](https://arxiv.org/abs/1907.12087)) to train the backbone.

**Comment by WindFall-wyx** [comment]
Thanks for your reply. But your paper says that "we use the TAFSSL protocol (and thus
their features) for the common testbed with other methods". Does it mean you directly use their features? Or train all the backbones, such as Resnet12, WRN, Densenet, with the same method S2M2?

**Comment by allenhaozhu** [comment]
> Thanks for your reply. But your paper says that "we use the TAFSSL protocol (and thus their features) for the common testbed with other methods". Does it mean you directly use their features? Or train all the backbones, such as Resnet12, WRN, Densenet, with the same method S2M2?

ResNet12 and WRN are with S2M2. DenseNet is with SimpleShot ([Revisiting Nearest-Neighbor Classification for Few-Shot](https://www.researchgate.net/publication/337208667_SimpleShot_Revisiting_Nearest-Neighbor_Classification_for_Few-Shot_Learning)). You know they are from different strategies. Yes I only use their features. But I trained this before, it is easy to have a backnone with a similar performance. I use features directly to compare other methods fairly (they also use).

**Comment by WindFall-wyx** [comment]
Agreed on this, the effectiveness of EASE is consistent. Thank you.
